data-dir = "./data"
#compression = ""

# log-file = ""
# log-rotate = "hour"
log-level = "debug"

# The timestmap is in nanosecond.
# start-ts = 
# end-ts = 

# dest-type choose a destination, which value can be "mysql","tidb", "print". 
# for print, it just print decoded value.
dest-type = "tidb"

##replicate-do-db priority over replicate-do-table if have same db name
##and we support regular expression , start with '~' declare use regular expression.
#
#replicate-do-db = ["~^b.*","s1"]
#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "log"

#[[replicate-do-table]]
#db-name ="test"
#tbl-name = "~^a.*"

[savepoint]
type = "file"
name = "savepoint"

[dest-db]
host = "127.0.0.1"
port = 4000
user = "root"
password = ""